[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
    # Use custom linker script.
    "-Clink-arg=-Tsrc/linker.ld",
    # Require the compiler not to omit frame pointers.
    "-Cforce-frame-pointers=yes",
]